-- Rulează în Supabase > SQL Editor. Înlocuiește ADMIN_EMAIL înainte de Run.
create table if not exists public.feedback (id bigint generated by default as identity primary key,created_at timestamptz not null default now(),category text not null check(char_length(category) between 2 and 80),message text not null check(char_length(message) between 5 and 4000),name text check(name is null or char_length(name)<=100),email text check(email is null or char_length(email)<=200),program text not null default 'both' check(program in ('AMG','TD','both')),page text,status text not null default 'nou' check(status in ('nou','in_lucru','rezolvat')));
alter table public.feedback enable row level security;
revoke all on table public.feedback from anon,authenticated;
grant insert on table public.feedback to anon;
grant select,update,delete on table public.feedback to authenticated;
create policy "public insert feedback" on public.feedback for insert to anon with check(status='nou');
create policy "admin select feedback" on public.feedback for select to authenticated using((select auth.jwt()->>'email')='ADMIN_EMAIL');
create policy "admin update feedback" on public.feedback for update to authenticated using((select auth.jwt()->>'email')='ADMIN_EMAIL') with check((select auth.jwt()->>'email')='ADMIN_EMAIL');
create policy "admin delete feedback" on public.feedback for delete to authenticated using((select auth.jwt()->>'email')='ADMIN_EMAIL');