-- CampusMed: Update-uri publice + Roadmap administrabil
create table if not exists public.portal_updates (id bigint generated by default as identity primary key,created_at timestamptz not null default now(),type text not null check(type in ('update','roadmap')),title text not null check(char_length(title) between 2 and 140),description text check(description is null or char_length(description)<=1000),status text not null default 'planificat' check(status in ('publicat','planificat','in_lucru')),event_date date,sort_order integer not null default 100,visible boolean not null default true);
alter table public.portal_updates enable row level security;
revoke all on table public.portal_updates from anon,authenticated;
grant select on table public.portal_updates to anon,authenticated;
grant insert,update,delete on table public.portal_updates to authenticated;
drop policy if exists "public read visible portal updates" on public.portal_updates;
drop policy if exists "authenticated read portal updates" on public.portal_updates;
drop policy if exists "admin insert portal updates" on public.portal_updates;
drop policy if exists "admin update portal updates" on public.portal_updates;
drop policy if exists "admin delete portal updates" on public.portal_updates;
create policy "public read visible portal updates" on public.portal_updates for select to anon using(visible=true);
create policy "authenticated read portal updates" on public.portal_updates for select to authenticated using(((select auth.jwt())->>'email')='gabi1dudan@gmail.com');
create policy "admin insert portal updates" on public.portal_updates for insert to authenticated with check(((select auth.jwt())->>'email')='gabi1dudan@gmail.com');
create policy "admin update portal updates" on public.portal_updates for update to authenticated using(((select auth.jwt())->>'email')='gabi1dudan@gmail.com') with check(((select auth.jwt())->>'email')='gabi1dudan@gmail.com');
create policy "admin delete portal updates" on public.portal_updates for delete to authenticated using(((select auth.jwt())->>'email')='gabi1dudan@gmail.com');
create index if not exists portal_updates_visible_sort_idx on public.portal_updates(visible,sort_order,created_at desc);
