-- CampusMed: Update-uri publice + Roadmap administrabil
-- Rulează o singură dată în Supabase > SQL Editor.
create table if not exists public.portal_updates (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  type text not null check(type in ('update','roadmap')),
  title text not null check(char_length(title) between 2 and 140),
  description text check(description is null or char_length(description)<=1000),
  status text not null default 'planificat' check(status in ('publicat','planificat','in_lucru')),
  event_date date,
  sort_order integer not null default 100,
  visible boolean not null default true
);
alter table public.portal_updates enable row level security;
revoke all on table public.portal_updates from anon,authenticated;
grant select on table public.portal_updates to anon,authenticated;
grant insert,update,delete on table public.portal_updates to authenticated;

create policy "public read visible portal updates" on public.portal_updates for select to anon using(visible=true);
create policy "authenticated read portal updates" on public.portal_updates for select to authenticated using((select auth.jwt()->>'email')='gabi1dudan@gmail.com');
create policy "admin insert portal updates" on public.portal_updates for insert to authenticated with check((select auth.jwt()->>'email')='gabi1dudan@gmail.com');
create policy "admin update portal updates" on public.portal_updates for update to authenticated using((select auth.jwt()->>'email')='gabi1dudan@gmail.com') with check((select auth.jwt()->>'email')='gabi1dudan@gmail.com');
create policy "admin delete portal updates" on public.portal_updates for delete to authenticated using((select auth.jwt()->>'email')='gabi1dudan@gmail.com');

insert into public.portal_updates(type,title,description,status,event_date,sort_order,visible) values
('update','CampusMed: optimizare frontend','Căutarea și documentele folosesc debounce, PWA-ul a fost optimizat și au fost adăugate teste automate pentru frontend.','publicat',current_date,10,true),
('roadmap','Extinderea paginilor pentru anii de studiu','Pregătirea unor spații dedicate și pentru ceilalți ani, pe măsură ce adăugăm informațiile necesare.','planificat',null,20,true);
